spring:
  docker:
    compose:
      enabled: false
  application:
    name: gym-management
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_management
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
  h2:
    console:
      enabled: false
      path: /h2-console
  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:http://localhost:4318/v1/metrics}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
    logging:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_LOGS_ENDPOINT:http://localhost:4318/v1/logs}
  mail:
    host: ${MAIL_HOST:smtp-relay.brevo.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:af5770001@smtp-brevo.com}
    password: ${MAIL_PASSWORD:bskKqlkelbtYYgF}
    from: ${MAIL_FROM:verifyy.testt@gmail.com}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    secret: ${JWT_SECRET:IhOKpzNEWKKpkQXoOLDCVdJ7zSKXtavXbPidtf+kFSETu5r2de7jhjO5ntlUvgc0+ZP2w2y1KIXuCZNNCjtPQw==}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  #    include: '*'
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

server:
  shutdown: immediate

logging:
  level:
    com.epam.gymmanagement: INFO
    org.springframework.boot.actuator.autoconfigure.opentelemetry: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){magenta} %clr(%-5level) %clr([%X{transactionId}]){cyan} %clr(%logger{36}){blue} %clr(-){faint} %msg%n"

kind: Application

# Separate configuration for different environments - logging
