#spring.application.name=gym-management
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/gym_management
#spring.datasource.username=postgres
#spring.datasource.password=2812
#spring.datasource.driver-class-name=org.postgresql.Driver
##spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=update
#spring.ai.vectorstore.pgvector.initialize-schema=true
#
#
##spring.datasource.url=jdbc:h2:mem:gym-management;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
##spring.datasource.driver-class-name=org.h2.Driver
##spring.datasource.username=sa
##spring.datasource.password=
##spring.jpa.hibernate.ddl-auto=update
#spring.jpa.open-in-view=false
#spring.h2.console.enabled=true
#
#security.jwt.secret=${JWT_SECRET:IhOKpzNEWKKpkQXoOLDCVdJ7zSKXtavXbPidtf+kFSETu5r2de7jhjO5ntlUvgc0+ZP2w2y1KIXuCZNNCjtPQw==}
#security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
